version: 0.0
os: linux
files:
  - source: /
    destination: /usr/TrackAppsBackend
    overwrite: true
permissions:
  - object: /usr/TrackAppsBackend
    pattern: "*.sh"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: codedeploy/before_install.sh
      timeout: 180
  AfterInstall:
    - location: codedeploy/after_install.sh
      timeout: 180
  ApplicationStart:
    - location: codedeploy/app_start.sh
      timeout: 180
  ValidateService:
    - location: codedeploy/validate_service.sh
      timeout: 180
